name: R Build and Checks
on: [push, pull_request]

jobs:
  build:
    name: R Build and Checks
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: R Build and Checks
      uses: Swechhya/R-actions@v1.2
      with:
        action: 'all'
        needsBioc: false
